{% set version = "4.2.1" %}

package:
  name: pillow
  version: {{ version }}

source:
  fn: Pillow-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/Pillow/Pillow-{{ version }}.tar.gz
  sha256: c724f65870e545316f9e82e4c6d608ab5aa9dd82d5185e5b2e72119378740073
  patches:
    - backport_pr_2624.patch

build:
  number: 5

requirements:
  build:
    - python
    - setuptools
    - zlib 1.2.8
    - libtiff >=4.0.3,<4.0.8
    - libjpeg-turbo *
    - freetype 2.7
    - tk 8.5.*
  run:
    - python
    - libjpeg-turbo *
    - zlib 1.2.8
    - freetype 2.7
    - libtiff >=4.0.3,<4.0.8
    - olefile

test:
  imports:
    - PIL
    - PIL.Image
  commands:
    - conda inspect linkages -p $PREFIX pillow  # [not win]
    - conda inspect objects -p $PREFIX pillow  # [osx]

about:
  home: http://python-imaging.github.io/
  license: PIL
  license_file: LICENSE
  summary: 'Pillow is the friendly PIL fork by Alex Clark and Contributors.'

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
